default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: osfx
development:
  <<: *default
  database: yandex-mailbox_development
test:
  <<: *default
  database: yandex-mailbox_test
production:
  <<: *default
  database: yandex-mailbox_production
  username: yandex-mailbox
  password: <%= ENV['YANDEX-MAILBOX_DATABASE_PASSWORD'] %>
